In [1]:
import numpy as np

In [4]:
print(np.__version__)

1.21.5


In [5]:
list = [1,2,3,4,5]
list1 = np.array(list)
print(list1)

[1 2 3 4 5]


In [7]:
list3 = [[1,2],[3,4],[5,6]]
list4  = np.array(list3)
print(list4)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
list2 = np.arange(11)
print(list2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [14]:
list5 = np.arange(0,10,2)
print(list5)

[0 2 4 6 8]


In [15]:
np.linspace(0,10,1)

array([0.])

In [17]:
np.ones(4, dtype=float)

array([1., 1., 1., 1.])

In [18]:
ar1 = np.array(["a","b","c","d","e"])
print(ar1)

['a' 'b' 'c' 'd' 'e']


In [19]:
print(ar1[2])

print(ar1[-1])



c
e


In [20]:
ar1 = np.array(["a", "b", "c", "d", "e"]) 

print(ar1[0] + ar1[2])

ar2 = np.array([1,2,3,4,5]) 

print(ar2[0] + ar2[2])                    # for array containing numbers we can add, subtract, multiply or divide
print(ar2[0] - ar2[2]) 
print(ar2[0] * ar2[2]) 
print(ar2[0] / ar2[2])


ac
4
-2
3
0.3333333333333333


In [5]:
arr = np.array([[1,2,3],[6,7,8]])
print('2nd element on 1st row', arr[0,1])
print('6th element on 2nd row', arr[1,2])

2nd element on 1st row 2
6th element on 2nd row 8


In [6]:
arr = np.array([[1,2,3],[6,7,8]])
print('2nd element on 1st row', arr[0,1])
print('6th element on 2nd row', arr[1,0])

2nd element on 1st row 2
6th element on 2nd row 6


In [21]:
ar2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (ar2)
print (ar2[0,1,1])
print (ar2[1,1,0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5
10


In [17]:
arr = np.array([[1,2,3],[6,7,8]])
print(arr[0,-1])

3


In [23]:
ar4 = np.array([1,2,3,4,5,6,7,8,9,10])
print(ar4[1:4])
print(ar4[1:10:2])

[2 3 4]
[ 2  4  6  8 10]


In [24]:
ar5 = np.array(["a","b","c","d","e"])
print(ar5[2:])
print(ar5[:5])

['c' 'd' 'e']
['a' 'b' 'c' 'd' 'e']


In [25]:
ar5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(ar5)

print(ar5[0, 1:4])



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[2 3 4]


In [29]:
np.delete(ar[6, 8])

NameError: name 'ar' is not defined

In [27]:
ar7 = np.array([2,50,96,100,10,6,5])

np.sort(ar7)


array([  2,   5,   6,  10,  50,  96, 100])

In [2]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])